version: "3.9"
services:
  identity:
    image: quay.io/keycloak/keycloak:24.0.3
    command: ['start-dev']
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB
      - KC_DB_URL
      - KC_DB_USERNAME
      - KC_PROXY
      - KC_DB_PASSWORD
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - lib-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      # MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/mysql_schema_init.sql"
    networks:
      - lib-network
networks:
  lib-network:
    driver: bridge
volumes:
  mysql-data: